### ISSUE TITLE
Is that possible to compile this repo in Windows?

### ISSUE THREAD

**Issue by ge79puv** [lzx1413/mediapipe-lite#2]
Hey there, 

I am really interested in your project, and I am trying to compile it in Windows 11, not in Ubuntu. When I run 'conan install . --build=missing -pr:h=docker/x86_gcc_profile', it turns out the error: "c++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files." "ERROR: gemmlowp/cci.20210928: Error in build() method, line 60  cmake.build()  ConanException: Error 2 while executing". What could be the potiential reason for this error? It seems that there is wrong configuration in CMakeList?

I already changed x86_gcc_profile (os=Windows). 

Thanks a lot in advance.

**Comment by lzx1413** [comment]
Thank you for your attention to our project. I have not tested the compilation on the Windows system yet. I will test it in the next few days and update the documentation. Please continue to pay attention.

**Comment by lzx1413** [comment]
@ge79puv I have tested the building process on windows, please refer to https://github.com/lzx1413/mediapipe-lite/blob/main/doc/build_with_msvc.md

**Comment by ge79puv** [comment]
@lzx1413 Thanks for your update. There is still the same error during 'conan install . --build=missing'. Could I know the version of your compiler? I guess that would be the reason. Following is mine:

**Comment by ge79puv** [comment]
@lzx1413 Thanks for your update. There is still the same error during 'conan install . --build=missing'. Could I know the version of your compiler? I guess that would be the reason. Following is mine: 
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows

**Comment by lzx1413** [comment]
You can try to run `conan profile detect` to generate the new default  profile for windows. I will update mine later.

**Comment by lzx1413** [comment]
@ge79puv this is my profile on windows
```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=193
os=Windows
```
