### ISSUE TITLE
ERROR: Error downloading file https://github.com/abseil/abseil-cpp/archive/20230125.1.tar.gz

### ISSUE THREAD

**Issue by bobibibo123** [lzx1413/mediapipe-lite#5]
Hello, when I execute the command “conan install . --build=missing -pr:h=docker/x86_gcc_profile”, the following error appears. It seems to be a network problem, but manual download is ok. Is there any solution to this?

======== Installing packages ========
abseil/20230125.1: WARN: Trying to remove corrupted source folder
abseil/20230125.1: WARN: This can take a while for big packages
abseil/20230125.1: Calling source() in /home/fqy/.conan2/p/absei555651ad2a7c7/s/src
abseil/20230125.1: ERROR: Error downloading file https://github.com/abseil/abseil-cpp/archive/20230125.1.tar.gz: 'HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /abseil/abseil-cpp/archive/20230125.1.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d63d76f28>: Failed to establish a new connection: [Errno 111] Connection refused',))'
abseil/20230125.1: Waiting 5 seconds to retry...
abseil/20230125.1: ERROR: Error downloading file https://github.com/abseil/abseil-cpp/archive/20230125.1.tar.gz: 'HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /abseil/abseil-cpp/archive/20230125.1.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d5d891ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))'
abseil/20230125.1: Waiting 5 seconds to retry...
ERROR: abseil/20230125.1: Error in source() method, line 81
	get(self, **self.conan_data["sources"][self.version], strip_root=True)
	ConanException: Error downloading file https://github.com/abseil/abseil-cpp/archive/20230125.1.tar.gz: 'HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /abseil/abseil-cpp/archive/20230125.1.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d5d85de48>: Failed to establish a new connection: [Errno 111] Connection refused',))'

**Comment by lzx1413** [comment]
Hello, my solution is Scientific Internet Access in the bash environment.🤭

**Comment by bobibibo123** [comment]
That's true, but it's also the above problem. I tried to use the wget command to download the file and put it locally, it didn't work either.
